const SB_URL="https://cybhsinaymvmgfwrhhvt.supabase.co",SB_KEY="sb_publishable_rlT-HHY5MTNgeBcNfLp01A_DCICFJzd",sb=window.supabase.createClient(SB_URL,SB_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let gameCache=[],downloadCounts={},activeCollectionId=null;

async function adminRequired(){
 try{
  const {data:{session}}=await sb.auth.getSession();if(!session)return false;
  const {data:a}=await sb.from("admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();
  if(!a){await sb.auth.signOut();$("#loginMsg").textContent="Esta conta não tem permissão de administrador.";return false}
  $("#gate").hidden=true;$("#adminApp").hidden=false;$("#adminName").textContent=session.user.email||"Admin";await loadDashboard();return true;
 }catch(e){console.error(e);$("#loginMsg").textContent="Erro ao validar administrador.";return false}
}
$("#loginForm").onsubmit=async e=>{e.preventDefault();const b=$("#loginForm button");b.disabled=true;$("#loginMsg").textContent="Entrando...";const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginMsg").textContent="E-mail ou senha inválidos.";else await adminRequired();b.disabled=false};
$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};

function showPage(id){$$(".page").forEach(x=>x.hidden=x.id!==id);$$("aside nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#pageTitle").textContent=({newgame:"Novo jogo",games:"Jogos",collections:"Coleções",reports:"Denúncias",broken:"Links quebrados",site:"Site",dashboard:"Dashboard"})[id]||id;if(id==="games")loadGames();if(id==="collections")loadCollections();if(id==="reports"||id==="broken")loadDashboard();window.scrollTo(0,0)}
$$("aside nav button").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$("#newGameBtn").onclick=()=>{resetForm();showPage("newgame")};
$("#cancelGameEdit").onclick=e=>{e.preventDefault();resetForm();showPage("games")};

async function logActivity(action,entityType,entityId,details=""){const {data:{session}}=await sb.auth.getSession();if(session)await sb.from("admin_activity").insert({admin_id:session.user.id,action,entity_type:entityType,entity_id:String(entityId||""),details})}

async function loadDashboard(){
 const since=new Date(Date.now()-30*864e5).toISOString();
 const [views,downloads,reports,broken,panelGames,comments,favorites,activity]=await Promise.all([
  sb.from("site_pageviews").select("path,visitor_id").gte("created_at",since),
  sb.from("game_downloads").select("game_slug,created_at"),
  sb.from("comment_reports").select("id,comment_id,reason,status,created_at").eq("status","open"),
  sb.from("broken_link_reports").select("id,game_slug,status,created_at").eq("status","open"),
  sb.from("admin_games").select("id,slug,title").eq("status","published"),
  sb.from("game_comments").select("id,game_slug,user_id,content,created_at"),
  sb.from("game_favorites").select("game_slug"),
  sb.from("admin_activity").select("*").order("created_at",{ascending:false}).limit(12)
 ]);
 const dl=downloads.data||[],cr=comments.data||[],fav=favorites.data||[],rr=reports.data||[],br=broken.data||[];
 downloadCounts={};dl.forEach(x=>downloadCounts[x.game_slug]=(downloadCounts[x.game_slug]||0)+1);
 $("#publishedGames").textContent=(panelGames.data||[]).length;$("#downloadsTotal").textContent=dl.length;$("#commentReports").textContent=rr.length;$("#brokenReports").textContent=br.length;
 const names=Object.fromEntries((panelGames.data||[]).map(g=>[g.slug,g.title]));
 const ranking=(rows,key,target)=>{const m={};rows.forEach(x=>m[x[key]]=(m[x[key]]||0)+1);$(target).innerHTML=Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([g,n])=>'<div><span>'+esc(names[g]||g)+'</span><b>'+n+'</b></div>').join("")||"<p>Nenhum registro ainda.</p>"};
 ranking(dl,"game_slug","#downloadsByGame");ranking(cr,"game_slug","#commentsByGame");ranking(fav,"game_slug","#favoritesByGame");
 const days={};for(let i=29;i>=0;i--){const d=new Date(Date.now()-i*864e5).toISOString().slice(0,10);days[d]=0}dl.forEach(x=>{const d=String(x.created_at).slice(0,10);if(d in days)days[d]++});const mx=Math.max(1,...Object.values(days));$("#downloadsChart").innerHTML=Object.entries(days).map(([d,n])=>'<i title="'+d+': '+n+'" style="height:'+Math.max(3,n/mx*100)+'%"></i>').join("");
 const counts={};(views.data||[]).forEach(x=>counts[x.path]=(counts[x.path]||0)+1);$("#topPages").innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([p,n])=>'<div><span>'+esc(p)+'</span><b>'+n+'</b></div>').join("")||"<p>Sem acessos registrados.</p>";
 $("#activityRows").innerHTML=(activity.data||[]).map(x=>'<div class="activity"><b>'+esc(x.action)+'</b><span>'+esc(x.details||x.entity_id)+'</span><small>'+new Date(x.created_at).toLocaleString("pt-BR")+'</small></div>').join("")||"<p>Nenhuma atividade.</p>";
 await renderReports(rr,cr);renderBroken(br,names);
}
async function renderReports(reports,comments){
 const ids=[...new Set(comments.map(x=>x.user_id).filter(Boolean))],{data:profiles}=ids.length?await sb.from("profiles").select("id,username").in("id",ids):{data:[]};const pm=Object.fromEntries((profiles||[]).map(p=>[p.id,p.username]));
 $("#commentReportRows").innerHTML=reports.map(r=>{const c=comments.find(x=>x.id===r.comment_id);return '<div class="report-card"><div><b>@'+esc(pm[c?.user_id]||"usuário")+'</b><small>'+esc(c?.game_slug||"")+'</small><p>'+esc(c?.content||"Comentário não encontrado")+'</p><em>Motivo: '+esc(r.reason)+'</em></div><button onclick="keepComment(\''+r.id+'\')">Manter</button><button class="danger" onclick="removeReportedComment(\''+r.id+'\',\''+(c?.id||"")+'\')">Excluir comentário</button></div>'}).join("")||"<p>Nenhuma denúncia pendente.</p>";
}
function renderBroken(rows,names){$("#brokenReportRows").innerHTML=rows.map(x=>'<div class="report-card"><div><b>'+esc(names[x.game_slug]||x.game_slug)+'</b><p>Link reportado como quebrado.</p></div><button onclick="editBySlug(\''+x.game_slug+'\')">Editar link</button><button onclick="resolveBrokenReport(\''+x.id+'\')">Resolvido</button></div>').join("")||"<p>Nenhum link quebrado pendente.</p>"}
window.keepComment=async id=>{await sb.from("comment_reports").update({status:"dismissed"}).eq("id",id);await logActivity("Denúncia mantida","comment_report",id);loadDashboard()};
window.removeReportedComment=async(id,cid)=>{if(!confirm("Excluir este comentário do site?"))return;if(cid)await sb.from("game_comments").delete().eq("id",cid);await sb.from("comment_reports").update({status:"resolved"}).eq("id",id);await logActivity("Comentário removido","comment",cid);loadDashboard()};
window.resolveBrokenReport=async id=>{await sb.from("broken_link_reports").update({status:"resolved"}).eq("id",id);await logActivity("Link marcado como resolvido","broken_link",id);loadDashboard()};

async function loadGames(){
 const [{data},{data:downloads}]=await Promise.all([sb.from("admin_games").select("*").order("updated_at",{ascending:false}),sb.from("game_downloads").select("game_slug")]);gameCache=data||[];downloadCounts={};(downloads||[]).forEach(x=>downloadCounts[x.game_slug]=(downloadCounts[x.game_slug]||0)+1);
 const platforms=[...new Set(gameCache.map(g=>g.platform).filter(Boolean))].sort();$("#gamePlatformFilter").innerHTML='<option value="">Todos os consoles</option>'+platforms.map(x=>'<option>'+esc(x)+'</option>').join("");renderGames();
}
function renderGames(){const q=$("#gameSearch").value.toLowerCase(),pf=$("#gamePlatformFilter").value,sf=$("#gameStatusFilter").value;$("#gamesRows").innerHTML=gameCache.filter(g=>(g.title+" "+g.platform).toLowerCase().includes(q)&&(!pf||g.platform===pf)&&(!sf||g.status===sf)).map(g=>'<tr><td><div class="game-cell">'+(g.cover?'<img src="'+esc(g.cover)+'" alt="">':'')+'<div><b>'+esc(g.title)+'</b><small>'+esc(g.slug)+'</small></div></div></td><td>'+esc(g.platform)+'</td><td>'+esc(g.language)+'</td><td>'+Number(downloadCounts[g.slug]||0)+'</td><td><span class="badge '+g.status+'">'+({published:"Publicado",draft:"Rascunho",scheduled:"Agendado"}[g.status]||g.status)+'</span></td><td>'+new Date(g.updated_at).toLocaleDateString("pt-BR")+'</td><td class="actions"><button onclick="editGame(\''+g.id+'\')">Editar</button><button onclick="viewGame(\''+g.slug+'\')">Ver</button><button onclick="duplicateGame(\''+g.id+'\')">Duplicar</button><button class="danger" onclick="deleteGame(\''+g.id+'\')">Excluir</button></td></tr>').join("")}
$("#gameSearch").oninput=renderGames;$("#gamePlatformFilter").onchange=renderGames;$("#gameStatusFilter").onchange=renderGames;
function resetForm(){$("#gameForm").reset();$("#gameId").value="";$("#formTitle").textContent="Adicionar jogo";$("#gameMsg").textContent="";$(".editor-tabs button")?.click();syncPreviews()}
window.editGame=id=>{const g=gameCache.find(x=>x.id===id);if(!g)return;showPage("newgame");$("#gameId").value=g.id;$("#formTitle").textContent="Editar jogo";Object.keys(g).forEach(k=>{const el=$("#gameForm").elements[k];if(!el)return;if(el.type==="checkbox")el.checked=!!g[k];else if(k==="screenshots")el.value=(g[k]||[]).join("\n");else if(k==="scheduled_at"&&g[k])el.value=new Date(g[k]).toISOString().slice(0,16);else el.value=g[k]??""});const gd=g.guide_data||{};const fm=$("#gameForm").elements;fm.guide_difficulty.value=gd.difficulty||"";fm.guide_time.value=gd.estimatedTime||"";fm.guide_playthroughs.value=gd.playthroughs||"";fm.guide_missables.value=gd.missables||"";fm.guide_summary.value=gd.summary||"";syncPreviews()};
window.editBySlug=async slug=>{await loadGames();const g=gameCache.find(x=>x.slug===slug);if(g)editGame(g.id)};
window.viewGame=slug=>window.open("/game/"+encodeURIComponent(slug),"_blank");
window.duplicateGame=async id=>{const g=gameCache.find(x=>x.id===id);if(!g)return;const copy={...g};delete copy.id;delete copy.created_at;copy.title+=" (Cópia)";copy.slug+="-copia";copy.status="draft";copy.published_at=null;copy.updated_at=new Date().toISOString();const {data,error}=await sb.from("admin_games").insert(copy).select().single();if(error)return alert(error.message);await logActivity("Jogo duplicado","game",data.id,data.title);loadGames()};
window.deleteGame=async id=>{const g=gameCache.find(x=>x.id===id);if(!confirm("Excluir "+(g?.title||"este jogo")+"?"))return;const {error}=await sb.from("admin_games").delete().eq("id",id);if(error)return alert(error.message);await logActivity("Jogo excluído","game",id,g?.title||"");loadGames();loadDashboard()};

$$(".editor-tabs button").forEach(b=>b.onclick=()=>{$$(".editor-tabs button").forEach(x=>x.classList.toggle("active",x===b));$$("[data-editor-panel]").forEach(p=>p.hidden=p.dataset.editorPanel!==b.dataset.editorTab)});
function payload(status){const fd=new FormData($("#gameForm")),o=Object.fromEntries(fd.entries());o.retroachievements_game_id=o.retroachievements_game_id?Number(o.retroachievements_game_id):null;o.rating=o.rating?Number(o.rating):null;o.screenshots=(o.screenshots||"").split("\n").map(x=>x.trim()).filter(Boolean);o.featured=$("#gameForm").elements.featured.checked;o.guide_data={available:!!o.guide_summary,difficulty:o.guide_difficulty||"—",estimatedTime:o.guide_time||"—",playthroughs:o.guide_playthroughs||"—",missables:o.guide_missables||"—",summary:o.guide_summary||"",steps:[],achievements:[]};delete o.guide_difficulty;delete o.guide_time;delete o.guide_playthroughs;delete o.guide_missables;delete o.guide_summary;o.status=status;o.updated_at=new Date().toISOString();o.scheduled_at=o.scheduled_at?new Date(o.scheduled_at).toISOString():null;if(status==="published")o.published_at=new Date().toISOString();return o}
async function save(status){const id=$("#gameId").value,p=payload(status),r=id?await sb.from("admin_games").update(p).eq("id",id).select().single():await sb.from("admin_games").insert(p).select().single();$("#gameMsg").textContent=r.error?r.error.message:({published:"Jogo publicado no site.",draft:"Rascunho salvo.",scheduled:"Publicação agendada."}[status]);if(r.error)return;if(r.data)$("#gameId").value=r.data.id;await logActivity(status==="published"?"Jogo publicado":status==="scheduled"?"Jogo agendado":"Rascunho salvo","game",r.data.id,r.data.title);await loadGames();await loadDashboard()}
$("#gameForm").onsubmit=async e=>{e.preventDefault();await save("published")};$("#saveDraft").onclick=()=>save("draft");$("#scheduleGame").onclick=()=>{if(!$("#gameForm").elements.scheduled_at.value)return alert("Escolha a data e o horário.");save("scheduled")};$("#previewGame").onclick=()=>{const slug=$("#gameForm").elements.slug.value;if(slug)window.open("/game/"+encodeURIComponent(slug),"_blank")};

async function uploadMedia(file,kind){if(!file)return null;const slug=$("#gameForm").elements.slug.value||"novo-jogo",ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=slug+"/"+kind+"-"+Date.now()+"."+ext;const {error}=await sb.storage.from("game-media").upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from("game-media").getPublicUrl(path).data.publicUrl}
$("#coverUpload").onchange=async e=>{try{$("#gameForm").elements.cover.value=await uploadMedia(e.target.files[0],"cover");syncPreviews()}catch(x){alert(x.message)}};
$("#bannerUpload").onchange=async e=>{try{$("#gameForm").elements.banner.value=await uploadMedia(e.target.files[0],"banner");syncPreviews()}catch(x){alert(x.message)}};
$("#screensUpload").onchange=async e=>{try{const urls=[];for(const f of e.target.files)urls.push(await uploadMedia(f,"screenshot"));const ta=$("#gameForm").elements.screenshots;ta.value=[ta.value.trim(),...urls].filter(Boolean).join("\n")}catch(x){alert(x.message)}};
function syncPreviews(){const c=$("#gameForm").elements.cover.value,b=$("#gameForm").elements.banner.value;$("#coverPreview").src=c||"";$("#coverPreview").hidden=!c;$("#bannerPreview").src=b||"";$("#bannerPreview").hidden=!b}
$("#gameForm").elements.cover.oninput=syncPreviews;$("#gameForm").elements.banner.oninput=syncPreviews;

$("#fetchRA").onclick=async()=>{const id=$("#gameForm").elements.retroachievements_game_id.value;if(!id)return alert("Informe o ID.");$("#raMsg").textContent="Buscando...";try{const r=await fetch("/api/retroachievements?mode=game&gameId="+encodeURIComponent(id)),j=await r.json();if(!r.ok)throw new Error(j.error||"Erro");const f=$("#gameForm").elements;if(!f.title.value)f.title.value=j.Title||j.title||"";f.platform.value=j.ConsoleName||j.consoleName||f.platform.value;f.developer.value=j.Developer||j.developer||f.developer.value;f.publisher.value=j.Publisher||j.publisher||f.publisher.value;f.genre.value=j.Genre||j.genre||f.genre.value;const rel=j.Released||j.released;if(rel&&!f.year.value)f.year.value=String(rel).slice(0,4);$("#raMsg").textContent="Dados encontrados. Conquistas: "+(j.NumAchievements??j.numAchievements??"—");}catch(e){$("#raMsg").textContent=e.message}};

async function loadCollections(){const [{data:cols},{data:items}]=await Promise.all([sb.from("game_collections").select("*").order("created_at",{ascending:false}),sb.from("game_collection_items").select("*")]);const its=items||[];$("#collectionRows").innerHTML=(cols||[]).map(x=>'<div class="admin-row"><div><b>'+esc(x.title)+'</b><small>'+its.filter(i=>i.collection_id===x.id).length+' jogos · '+(x.status==="published"?"Publicada":"Rascunho")+'</small></div><button onclick="manageCollection(\''+x.id+'\',\''+esc(x.title).replaceAll("'","&#39;")+'\')">Editar jogos</button><button class="danger" onclick="deleteCollection(\''+x.id+'\')">Excluir</button></div>').join("")||"<p>Nenhuma coleção criada.</p>"}
$("#createCollection").onclick=async()=>{const title=$("#collectionTitle").value.trim();if(!title)return;const slug=title.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const {data,error}=await sb.from("game_collections").insert({title,slug,status:"published"}).select().single();if(error)return alert(error.message);await logActivity("Coleção criada","collection",data.id,title);$("#collectionTitle").value="";loadCollections()};
window.deleteCollection=async id=>{if(!confirm("Excluir esta coleção?"))return;await sb.from("game_collections").delete().eq("id",id);await logActivity("Coleção excluída","collection",id);loadCollections()};
window.manageCollection=async(id,title)=>{activeCollectionId=id;await loadGames();const {data}=await sb.from("game_collection_items").select("*").eq("collection_id",id).order("position");const pos=Object.fromEntries((data||[]).map((x,i)=>[x.game_slug,i+1]));$("#collectionEditorTitle").textContent=title;$("#collectionGamePicker").innerHTML=gameCache.filter(g=>g.status==="published").map(g=>'<label class="collection-game"><input type="checkbox" value="'+esc(g.slug)+'" '+(pos[g.slug]?"checked":"")+'><img src="'+esc(g.cover||"")+'" alt=""><span>'+esc(g.title)+'</span><input class="collection-pos" type="number" min="1" value="'+(pos[g.slug]||999)+'"></label>').join("");$("#collectionEditor").hidden=false};
$("#closeCollectionEditor").onclick=()=>{$("#collectionEditor").hidden=true;activeCollectionId=null};
$("#saveCollectionGames").onclick=async()=>{if(!activeCollectionId)return;const selected=$$("#collectionGamePicker .collection-game").filter(x=>x.querySelector('input[type="checkbox"]').checked).map(x=>({game_slug:x.querySelector('input[type="checkbox"]').value,position:Number(x.querySelector(".collection-pos").value)||999})).sort((a,b)=>a.position-b.position).map((x,i)=>({...x,position:i}));await sb.from("game_collection_items").delete().eq("collection_id",activeCollectionId);if(selected.length)await sb.from("game_collection_items").insert(selected.map(x=>({...x,collection_id:activeCollectionId})));await logActivity("Coleção atualizada","collection",activeCollectionId,selected.length+" jogos");$("#collectionEditor").hidden=true;loadCollections()};

adminRequired();